services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app