apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: 699510596669.dkr.ecr.ap-northeast-2.amazonaws.com/auth:latest
        name: auth
        env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: mysql
                key: MYSQL_HOST
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: MYSQL_PASSWORD
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: mysql
                key: MYSQL_PORT
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql
                key: MYSQL_USERNAME
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwtSecret
          - name: TCP_PORT
            value: '3002'
          - name: HTTP_PORT
            value: '3003'
          - name: GOOGLE_CLIENT_ID
            value: 978767535383-equ6kdpkkfio1sv4tu03dovo6mipf77o.apps.googleusercontent.com
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_CALLBACK_URL
            valueFrom:
              secretKeyRef:
                name: google
                key: callbackUrl
          - name: RABBITMQ_URI
            value: amqp://rabbitmq:5672
        ports:
          - containerPort: 3002
          - containerPort: 3003
        livenessProbe:
          httpGet:
            path: /livez/
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
            httpGet:
                path: /readyz/
                port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5