apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: 699510596669.dkr.ecr.ap-northeast-2.amazonaws.com/reservations:latest
        name: reservations
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: PORT
            value: '3004'
          - name: AUTH_HOST
            value: auth-tcp
          - name: AUTH_PORT
            value: '3002'
          - name: NOTIFICATIONS_HOST
            value: notifications
          - name: NOTIFICATIONS_PORT
            value: '3000'
        ports:
          - containerPort: 3004
        livenessProbe:
            httpGet:
                path: /livez/
                port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5
        readinessProbe:
            httpGet:
                path: /readyz/
                port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5